on:
    push:
        paths:
            - packages/style/**

jobs:
    a11y:
        timeout-minutes: 1
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - name: Install dependencies
              run: bun install
                  bunx playwright install
            - name: Run Storybook tests
              run: cd packages/style && bun test-storybook:ci
